# ----
# Site

title: Partners Api Documentation
description: Documentation for the on-demand design Creads Partners API
url: https://www.creads-partners.com
google_analytics_key:
permalink: pretty
baseurl: '/partners-doc'

collections:
  overview:
    title: Overview
    alphabetical: false
    position: 1
  oauth2:
    title: OAuth2
    alphabetical: false
    position: 2
  resources:
    title: Ressources
    alphabetical: false
    position: 3
  api:
    title: API
    alphabetical: true
    position: 4

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
